<?php

/**
 * BasePaginas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $pagina
 * @property text $contenido
 * @property string $imagen
 * @property string $fondo
 * 
 * @method string  getPagina()    Returns the current record's "pagina" value
 * @method text    getContenido() Returns the current record's "contenido" value
 * @method string  getImagen()    Returns the current record's "imagen" value
 * @method string  getFondo()     Returns the current record's "fondo" value
 * @method Paginas setPagina()    Sets the current record's "pagina" value
 * @method Paginas setContenido() Sets the current record's "contenido" value
 * @method Paginas setImagen()    Sets the current record's "imagen" value
 * @method Paginas setFondo()     Sets the current record's "fondo" value
 * 
 * @package    Botica
 * @subpackage model
 * @author     Ricardo Alcantara <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePaginas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('paginas');
        $this->hasColumn('pagina', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('contenido', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('imagen', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('fondo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'pagina',
             ),
             'unique' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}