<?php

/**
 * BaseCategoriasProyectos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $categoria
 * @property string $slug
 * @property boolean $is_active
 * @property Doctrine_Collection $Proyectos
 * 
 * @method string              getCategoria() Returns the current record's "categoria" value
 * @method string              getSlug()      Returns the current record's "slug" value
 * @method boolean             getIsActive()  Returns the current record's "is_active" value
 * @method Doctrine_Collection getProyectos() Returns the current record's "Proyectos" collection
 * @method CategoriasProyectos setCategoria() Sets the current record's "categoria" value
 * @method CategoriasProyectos setSlug()      Sets the current record's "slug" value
 * @method CategoriasProyectos setIsActive()  Sets the current record's "is_active" value
 * @method CategoriasProyectos setProyectos() Sets the current record's "Proyectos" collection
 * 
 * @package    Botica
 * @subpackage model
 * @author     Ricardo Alcantara <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoriasProyectos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('categorias_proyectos');
        $this->hasColumn('categoria', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Proyectos', array(
             'local' => 'id',
             'foreign' => 'categoria_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sortable0 = new Doctrine_Template_Sortable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'categoria',
             ),
             'unique' => true,
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sortable0);
        $this->actAs($sluggable0);
    }
}