<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/03/01 05:55:02

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=phrenesi_botica',
  'username' => 'phrenesi_rpsstms',
  'password' => 'D3m3s1s1',
  'persistent' => true,
  'name' => 'doctrine',
)),);
