<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/08/17 12:50:49
$this->security = array (
  'construccion' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
