<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/03/01 05:55:03
$this->security = array (
  'construccion' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
