<?php

/**
 * Clientes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Botica
 * @subpackage model
 * @author     Ricardo Alcantara <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Clientes extends BaseClientes
{
    public function save(Doctrine_Connection $conn = null) {
        
        $imagen=$this->getImagen();
        $path= sfConfig::get('sf_upload_dir').'/clientes/';
        if(file_exists($path.$imagen)){
           $img = new sfImage($path.$imagen, sfRichSys::getTipoMime($imagen));
           $height=$img->getHeight();
           $width=$img->getWidth();
           if($height>100 || $iwidth>200){
               sfRichSys::crearImagenClientes($path,$imagen,$this->isNew());
           }
        }else{
           $this->setImagen("sin_imagen.jpg");  
        } 
        
        
        parent::save($conn);
    }
}