<?php

/**
 * Configuracion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Botica
 * @subpackage model
 * @author     Richpolis Systems <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Configuracion extends BaseConfiguracion
{
}
