<?php

/**
 * Paginas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Botica
 * @subpackage model
 * @author     Ricardo Alcantara <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Paginas extends BasePaginas
{
    public function getContenidoCorto($max=200){
        if($this->getContenido()){
            //$texto=htmlentitites($this->getContenido());
            $texto = strip_tags($this->getContenido());
            //$texto=  str_replace("&amp;", "&", $texto);
            return sfRichSys::cut_string($texto,$max);
        }else{
            return "Sin contenido";
        }
    }

}