<?php

/**
 * PaginasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PaginasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PaginasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Paginas');
    }
}