# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Botica
    description:  Botica
    keywords:     Botica
    language:     es
    #robots:       index, follow

  stylesheets:    [reset.css,main.css]

  javascripts:    [jquery.min.js,jquery.smartBackgroundResize-1.0.js]

  has_layout:     true
  layout:         layout1
