<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/08/17 12:50:46
sfConfig::add(array(
  'app_sfImageTransformPlugin_default_adapter' => 'GD',
  'app_sfImageTransformPlugin_default_image' => array (
  'mime_type' => 'image/png',
  'filename' => 'Untitled.png',
  'width' => 100,
  'height' => 100,
  'color' => '#000000',
),
  'app_sfImageTransformPlugin_font_dir' => '/usr/share/fonts/truetype/msttcorefonts',
  'app_sfImageTransformPlugin_mime_type' => array (
  'auto_detect' => true,
  'library' => 'gd_mime_type',
),
  'app_sf_admin_dash_web_dir' => '/sfAdminDashPlugin',
  'app_sf_admin_dash_image_dir' => '/sfAdminDashPlugin/images/icons/',
  'app_sf_admin_dash_default_image' => 'config.png',
  'app_sf_admin_dash_resize_mode' => 'thumbnail',
  'app_sf_admin_dash_logout' => true,
  'app_sf_admin_dash_site' => 'Botica',
  'app_sf_admin_dash_include_path' => true,
  'app_sf_admin_dash_include_jquery_no_conflict' => false,
  'app_sf_admin_dash_login_route' => '@sf_guard_signin',
  'app_sf_admin_dash_logout_route' => '@sf_guard_signout',
  'app_sf_admin_dash_categories' => array (
  'Administracion' => 
  array (
    'items' => 
    array (
      'Usuarios' => 
      array (
        'url' => 'sf_guard_user',
        'image' => 'users.png',
        'credentials' => 
        array (
          0 => 'admin',
        ),
      ),
      'Grupos' => 
      array (
        'url' => 'sf_guard_group',
        'image' => 'addusers.png',
        'credentials' => 
        array (
          0 => 'admin',
        ),
      ),
      'Permisos' => 
      array (
        'url' => 'sf_guard_permission',
        'image' => 'config.png',
        'credentials' => 
        array (
          0 => 'admin',
        ),
      ),
      'Configuracion' => 
      array (
        'url' => 'configuracion',
        'image' => 'cpanel.png',
        'credentials' => 
        array (
          0 => 'admin',
        ),
      ),
      'Paginas' => 
      array (
        'url' => 'paginas',
        'image' => 'cpanel.png',
        'credentials' => 
        array (
          0 => 'admin',
        ),
      ),
    ),
  ),
  'Publicaciones' => 
  array (
    'items' => 
    array (
      'Publicaciones' => 
      array (
        'url' => 'categorias_publicaciones',
        'image' => 'mediamanager.png',
        'credentials' => 
        array (
          0 => 
          array (
            0 => 'publicaciones',
            1 => 'admin',
          ),
        ),
      ),
      'Portafolio' => 
      array (
        'url' => 'categorias_proyectos',
        'image' => 'mediamanager.png',
        'credentials' => 
        array (
          0 => 
          array (
            0 => 'publicaciones',
            1 => 'admin',
          ),
        ),
      ),
      'Clientes' => 
      array (
        'url' => 'clientes',
        'image' => 'mediamanager.png',
        'credentials' => 
        array (
          0 => 
          array (
            0 => 'publicaciones',
            1 => 'admin',
          ),
        ),
      ),
    ),
  ),
),
));
