<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/08/17 12:50:47

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sfbotica',
  'username' => 'root',
  'password' => 'root',
  'persistent' => true,
  'name' => 'doctrine',
)),);
