<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/03/01 05:52:50

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sfbotica',
  'username' => 'root',
  'password' => 'root',
  'persistent' => true,
  'name' => 'doctrine',
)),);
