<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/03/04 22:35:47
$this->security = array (
  'construccion' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
